trigger:
  batch: true
  branches:
    include:
      - main

resources:
  repositories:
    - repository: self
      type: github
      connection: github-bestrong-connection
      name: $(Build.Repository.Name)
      ref: $(Build.SourceBranch)

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: terraformVersion
    value: '1.5.7'
  - name: workingDirectory
    value: '$(System.DefaultWorkingDirectory)'
  - group: terraform-variables

stages:
  - stage: CI_CD
    displayName: 'CI/CD Pipeline'
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest')))
    jobs:
      - job: DeployTerraform
        displayName: 'Deploy Infrastructure'
        steps:
          - checkout: self

          - task: Bash@3
            displayName: 'Install Terraform $(terraformVersion) via apt'
            inputs:
              targetType: 'inline'
              script: |
                echo "Updating package list and installing dependencies..."
                sudo apt-get update
                sudo apt-get install -y gnupg software-properties-common curl lsb-release

                echo "Adding HashiCorp official repository..."
                curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
                sudo apt-add-repository "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                sudo apt-get update

                echo "Installing Terraform..."
                sudo apt-get install terraform=$(terraformVersion) -y
                terraform version

          - task: DownloadSecureFile@1
            name: envFile
            displayName: 'Download Terraform Environment File'
            inputs:
              secureFile: 'terraform.env'

          - task: Bash@3
            displayName: 'Convert Environment File to Unix Format'
            inputs:
              targetType: 'inline'
              script: |
                tr -d '\r' < "$(envFile.secureFilePath)" > unix_env_file.tmp
                cp unix_env_file.tmp "$(envFile.secureFilePath)"
                rm unix_env_file.tmp
                echo "Environment file converted to Unix format"

          - task: AzureCLI@2
            displayName: 'Terraform Init'
            inputs:
              azureSubscription: 'bestrong-azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -a
                source $(envFile.secureFilePath)
                set +a
                
                export TF_VAR_subscription_id=$(echo "$TF_VAR_subscription_id" | tr -d '\r')
                echo "Using subscription ID: $TF_VAR_subscription_id"
                
                terraform init \
                  -backend-config="storage_account_name=$(TF_STATE_SA)" \
                  -backend-config="container_name=$(TF_STATE_CONTAINER)" \
                  -backend-config="resource_group_name=$(TF_STATE_RG)"
              workingDirectory: '$(workingDirectory)'

          - task: AzureCLI@2
            displayName: 'Terraform Validate'
            inputs:
              azureSubscription: 'bestrong-azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -a
                source $(envFile.secureFilePath)
                set +a
                
                export TF_VAR_subscription_id=$(echo "$TF_VAR_subscription_id" | tr -d '\r')
                echo "Using subscription ID: $TF_VAR_subscription_id"
                
                terraform validate
              workingDirectory: '$(workingDirectory)'

          - task: AzureCLI@2
            displayName: 'Terraform Plan'
            inputs:
              azureSubscription: 'bestrong-azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -a
                source $(envFile.secureFilePath)
                set +a
                
                export TF_VAR_subscription_id=$(echo "$TF_VAR_subscription_id" | tr -d '\r')
                echo "Using subscription ID: $TF_VAR_subscription_id"
                
                terraform plan
              workingDirectory: '$(workingDirectory)'

          - task: AzureCLI@2
            displayName: 'Terraform Apply'
            inputs:
              azureSubscription: 'bestrong-azure-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -a
                source $(envFile.secureFilePath)
                set +a
                
                export TF_VAR_subscription_id=$(echo "$TF_VAR_subscription_id" | tr -d '\r')
                echo "Using subscription ID: $TF_VAR_subscription_id"
                
                terraform apply -auto-approve tfplan
              workingDirectory: '$(workingDirectory)' 