name: Deploy-Terraform-Infrastructure

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: terraform-variables

jobs:
- job: DeployTerraform
  displayName: 'Deploy Terraform Infrastructure to Azure'
  steps:
  
  - task: DownloadSecureFile@1
    name: DownloadEnv
    displayName: 'Download .env Secure File'
    inputs:
      secureFile: '.env'

  - script: |
      echo "Current directory: $(pwd)"
      echo "Repository contents:"
      ls -la
      echo "Terraform directory contents:"
      ls -la terraform/
      
      echo ".env file line endings (Windows to Unix)..."
      sed -i 's/\r$//' $(DownloadEnv.secureFilePath)

      echo "Sourcing environment variables from .env..."
      set -a
      source $(DownloadEnv.secureFilePath)
      set +a
    displayName: 'Prepare Environment Variables'

  - task: UseTerraform@0
    displayName: 'Install Terraform CLI'
    inputs:
      terraformVersion: 'latest'

  - script: |
      cd $(System.DefaultWorkingDirectory)/terraform

      echo "Running Terraform init..."
      terraform init \
        -backend-config="resource_group_name=bestrong-tfstate-rg" \
        -backend-config="storage_account_name=bestrongtfstate" \
        -backend-config="container_name=tfstate" \
        -backend-config="key=terraform.tfstate"

      echo "Running Terraform plan..."
      terraform plan -out=tfplan

      echo "Running Terraform apply..."
      terraform apply -auto-approve tfplan
    workingDirectory: $(System.DefaultWorkingDirectory)/terraform
    displayName: 'Run Terraform Init, Plan and Apply'