location            = "westeurope"
resource_group_name = "bestrong-app-rg"
service_plan_name   = "bestrong-asp"
web_app_name        = "bestrong-web-app"
docker_image_name   = "bestrong-web-api:latest"
environment         = "Production"